
package InterfazGrafica;
import Backend.UsuarioLogic;
import javax.swing.JOptionPane;

/**
 *
 * @author Esteban
 */
public class PantallaLogin extends javax.swing.JFrame {

    public PantallaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelgreen = new javax.swing.JPanel();
        jPanelwhite = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        usuario = new javax.swing.JLabel();
        txtUsuarioLogin = new javax.swing.JTextField();
        contraseña = new javax.swing.JLabel();
        txtContraseniaLogin = new javax.swing.JPasswordField();
        Bingre = new javax.swing.JButton();
        Bsalir = new javax.swing.JButton();
        Bregistrar = new javax.swing.JButton();
        ChekMostrarcontrasenia = new javax.swing.JCheckBox();
        BLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(725, 330));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                Cerrar(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(720, 330));

        jPanelgreen.setBackground(new java.awt.Color(37, 152, 134));
        jPanelgreen.setPreferredSize(new java.awt.Dimension(720, 300));

        jPanelwhite.setBackground(new java.awt.Color(255, 255, 255));
        jPanelwhite.setPreferredSize(new java.awt.Dimension(275, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logo-Park-Point.png"))); // NOI18N

        jPanel9.setBackground(new java.awt.Color(218, 149, 0));
        jPanel9.setPreferredSize(new java.awt.Dimension(4, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelwhiteLayout = new javax.swing.GroupLayout(jPanelwhite);
        jPanelwhite.setLayout(jPanelwhiteLayout);
        jPanelwhiteLayout.setHorizontalGroup(
            jPanelwhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelwhiteLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(42, 42, 42))
        );
        jPanelwhiteLayout.setVerticalGroup(
            jPanelwhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
            .addGroup(jPanelwhiteLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        usuario.setBackground(new java.awt.Color(255, 255, 255));
        usuario.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("Usuario");

        txtUsuarioLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        contraseña.setBackground(new java.awt.Color(255, 255, 255));
        contraseña.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        contraseña.setForeground(new java.awt.Color(255, 255, 255));
        contraseña.setText("Contraseña");

        txtContraseniaLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtContraseniaLogin.setPreferredSize(new java.awt.Dimension(90, 18));

        Bingre.setBackground(new java.awt.Color(218, 149, 0));
        Bingre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Bingre.setForeground(new java.awt.Color(255, 255, 255));
        Bingre.setText("Ingresar");
        Bingre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bingre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BingreActionPerformed(evt);
            }
        });

        Bsalir.setBackground(new java.awt.Color(218, 149, 0));
        Bsalir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Bsalir.setForeground(new java.awt.Color(255, 255, 255));
        Bsalir.setText("Salir");
        Bsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsalirActionPerformed(evt);
            }
        });

        Bregistrar.setBackground(new java.awt.Color(218, 149, 0));
        Bregistrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Bregistrar.setForeground(new java.awt.Color(255, 255, 255));
        Bregistrar.setText("Registrar");
        Bregistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BregistrarActionPerformed(evt);
            }
        });

        ChekMostrarcontrasenia.setBackground(new java.awt.Color(37, 152, 134));
        ChekMostrarcontrasenia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ChekMostrarcontrasenia.setForeground(new java.awt.Color(255, 255, 255));
        ChekMostrarcontrasenia.setText("mostra contraseña");
        ChekMostrarcontrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChekMostrarcontraseniaActionPerformed(evt);
            }
        });

        BLimpiar.setBackground(new java.awt.Color(218, 149, 0));
        BLimpiar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        BLimpiar.setText("Limpiar");
        BLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelgreenLayout = new javax.swing.GroupLayout(jPanelgreen);
        jPanelgreen.setLayout(jPanelgreenLayout);
        jPanelgreenLayout.setHorizontalGroup(
            jPanelgreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelgreenLayout.createSequentialGroup()
                .addGroup(jPanelgreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelgreenLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(ChekMostrarcontrasenia)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelgreenLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelgreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelgreenLayout.createSequentialGroup()
                                .addComponent(Bregistrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Bingre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Bsalir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BLimpiar)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelgreenLayout.createSequentialGroup()
                                .addGroup(jPanelgreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(usuario)
                                    .addComponent(txtUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contraseña)
                                    .addComponent(txtContraseniaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(128, 128, 128)))))
                .addComponent(jPanelwhite, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelgreenLayout.setVerticalGroup(
            jPanelgreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelwhite, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
            .addGroup(jPanelgreenLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contraseña)
                .addGap(18, 18, 18)
                .addComponent(txtContraseniaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(ChekMostrarcontrasenia)
                .addGap(18, 18, 18)
                .addGroup(jPanelgreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bingre)
                    .addComponent(Bsalir)
                    .addComponent(Bregistrar)
                    .addComponent(BLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelgreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelgreen, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BsalirActionPerformed

    private void BingreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BingreActionPerformed
        
        if(!txtUsuarioLogin.getText().isEmpty()&&!txtContraseniaLogin.getText().isEmpty()){
            if(UsuarioLogic.autentificar(txtUsuarioLogin.getText(), txtContraseniaLogin.getText())){
               JOptionPane.showMessageDialog(null, "Bienvenido al sistema Park point");
               this.dispose();
               PantallaPrincipal pantallaprincipal=new PantallaPrincipal();
               pantallaprincipal.setVisible(true);
               pantallaprincipal.setLocationRelativeTo(null);
           }else{
               JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos");
               
           }
        }else{
        JOptionPane.showMessageDialog(null, "No ha ingresado usuario y contraseña");
       }
    }//GEN-LAST:event_BingreActionPerformed

    private void BregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BregistrarActionPerformed
        RegistroLogin registrologin = new RegistroLogin();
        registrologin.setVisible(true);
    }//GEN-LAST:event_BregistrarActionPerformed

    private void ChekMostrarcontraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChekMostrarcontraseniaActionPerformed
        if(ChekMostrarcontrasenia.isSelected()){
            txtContraseniaLogin.setEchoChar((char)0);
        
        }else{
        txtContraseniaLogin.setEchoChar('*');
        }
        
    }//GEN-LAST:event_ChekMostrarcontraseniaActionPerformed

    private void BLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLimpiarActionPerformed
        // TODO add your handling code here:
        txtUsuarioLogin.setText("");
        txtContraseniaLogin.setText("");
    }//GEN-LAST:event_BLimpiarActionPerformed

    private void Cerrar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Cerrar
       int result=JOptionPane.showConfirmDialog(this, "¿Desea salir de la aplicación?");
        
        if(result==JOptionPane.YES_OPTION){
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        }
    }//GEN-LAST:event_Cerrar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BLimpiar;
    private javax.swing.JButton Bingre;
    private javax.swing.JButton Bregistrar;
    private javax.swing.JButton Bsalir;
    private javax.swing.JCheckBox ChekMostrarcontrasenia;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelgreen;
    private javax.swing.JPanel jPanelwhite;
    private javax.swing.JPasswordField txtContraseniaLogin;
    private javax.swing.JTextField txtUsuarioLogin;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
