
package InterfazGrafica;

import Backend.UsuarioLogic;
import ClasesLogin.Usuario;
import javax.swing.JOptionPane;

public class RegistroLogin extends javax.swing.JFrame {

    public RegistroLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RtxtUsuario = new javax.swing.JTextField();
        RtxtCorreo = new javax.swing.JTextField();
        RtxtApellido = new javax.swing.JTextField();
        RtxtNombre = new javax.swing.JTextField();
        RtxtContrasenia = new javax.swing.JPasswordField();
        RtxtRepetirContrasenia = new javax.swing.JPasswordField();
        RbtnRegistrar = new javax.swing.JButton();
        RbtnModificar = new javax.swing.JButton();
        RbtnEliminar = new javax.swing.JButton();
        RbtnLimpiar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(37, 152, 134));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de Usuario");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Correo:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contraseña:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuario:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Repetir contraseña:");

        RbtnRegistrar.setBackground(new java.awt.Color(218, 149, 0));
        RbtnRegistrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        RbtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        RbtnRegistrar.setText("Registrar");
        RbtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnRegistrarActionPerformed(evt);
            }
        });

        RbtnModificar.setBackground(new java.awt.Color(218, 149, 0));
        RbtnModificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        RbtnModificar.setForeground(new java.awt.Color(255, 255, 255));
        RbtnModificar.setText("Modificar");
        RbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnModificarActionPerformed(evt);
            }
        });

        RbtnEliminar.setBackground(new java.awt.Color(218, 149, 0));
        RbtnEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        RbtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        RbtnEliminar.setText("Eliminar");
        RbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnEliminarActionPerformed(evt);
            }
        });

        RbtnLimpiar.setBackground(new java.awt.Color(218, 149, 0));
        RbtnLimpiar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        RbtnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        RbtnLimpiar.setText("Limpiar");
        RbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(65, 65, 65)
                                    .addComponent(jLabel5))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(RtxtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                .addComponent(RtxtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                .addComponent(RtxtContrasenia)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(115, 115, 115)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(RtxtRepetirContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(RtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(RtxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(RbtnRegistrar)
                        .addGap(18, 18, 18)
                        .addComponent(RbtnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(RbtnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(RbtnLimpiar)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(RtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RtxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RtxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(RtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(RtxtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(RtxtRepetirContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbtnRegistrar)
                    .addComponent(RbtnModificar)
                    .addComponent(RbtnEliminar)
                    .addComponent(RbtnLimpiar))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnEliminarActionPerformed
       if(RtxtUsuario.getText()!=null){
           if(UsuarioLogic.eliminar(RtxtUsuario.getText())){
           JOptionPane.showMessageDialog(null, "Usuario eliminado con exito");
           }else{
           JOptionPane.showMessageDialog(null, "Usuario no encontrado");
       }
       
       }
    }//GEN-LAST:event_RbtnEliminarActionPerformed

    private void RbtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnRegistrarActionPerformed
       if(!RtxtNombre.getText().isEmpty()&&
               !RtxtApellido.getText().isEmpty()&&
               !RtxtCorreo.getText().isEmpty()&&
               !RtxtUsuario.getText().isEmpty()&&
               !RtxtContrasenia.getText().isEmpty()&&
               RtxtRepetirContrasenia.getText().equals(RtxtContrasenia.getText())){
       
        
           Usuario usuario = new Usuario(RtxtUsuario.getText(),
           RtxtContrasenia.getText(), RtxtNombre.getText(), RtxtApellido.getText(),
           RtxtCorreo.getText());
           
           if(UsuarioLogic.insertar(usuario)){
           JOptionPane.showMessageDialog(null, "Usuario registrado con exito");
           }else{
           JOptionPane.showMessageDialog(null, "Usuario ya existente");
       }
       }else{
           JOptionPane.showMessageDialog(null, "No se han ingresado los datos en la casillas");
       }
       
    }//GEN-LAST:event_RbtnRegistrarActionPerformed

    private void RbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnModificarActionPerformed
        if(RtxtNombre.getText()!=null&&
               RtxtApellido.getText()!=null&&
               RtxtCorreo.getText()!=null&&
               RtxtUsuario.getText()!=null&&
               RtxtContrasenia.getText()!=null&&
               RtxtRepetirContrasenia.getText().equals(RtxtContrasenia.getText())){
       
           Usuario usuario = new Usuario(RtxtUsuario.getText(),
           RtxtContrasenia.getText(), RtxtNombre.getText(), RtxtApellido.getText(),
           RtxtCorreo.getText());
           if(UsuarioLogic.modificar(usuario)){
           JOptionPane.showMessageDialog(null, "Usuario modificado con exito");
           
           }else{
           JOptionPane.showMessageDialog(null, "Usuario no encontrado");
       }
       }else{
       JOptionPane.showMessageDialog(null, "No se han ingresado los datos en la casillas");
       }
    }//GEN-LAST:event_RbtnModificarActionPerformed

    private void RbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnLimpiarActionPerformed
        // TODO add your handling code here:
        RtxtNombre.setText("");
        RtxtApellido.setText("");
        RtxtCorreo.setText("");
        RtxtUsuario.setText("");
        RtxtContrasenia.setText("");
        RtxtRepetirContrasenia.setText("");
    }//GEN-LAST:event_RbtnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RegistroLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RbtnEliminar;
    private javax.swing.JButton RbtnLimpiar;
    private javax.swing.JButton RbtnModificar;
    private javax.swing.JButton RbtnRegistrar;
    private javax.swing.JTextField RtxtApellido;
    private javax.swing.JPasswordField RtxtContrasenia;
    private javax.swing.JTextField RtxtCorreo;
    private javax.swing.JTextField RtxtNombre;
    private javax.swing.JPasswordField RtxtRepetirContrasenia;
    private javax.swing.JTextField RtxtUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
